# Generated by Django 4.0.1 on 2022-03-03 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Team Name'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='team_capitan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_capitan', to=settings.AUTH_USER_MODEL),
        ),
    ]
