# Generated by Django 4.0.1 on 2022-03-05 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_rename_teammodel_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(max_length=15, verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league_link',
            field=models.URLField(verbose_name='Turnier.de'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='Spieler'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_capitan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_capitan', to=settings.AUTH_USER_MODEL, verbose_name='Mannschaftsführer'),
        ),
    ]
