# Generated by Django 4.0.1 on 2022-03-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OppClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Verein')),
            ],
        ),
        migrations.CreateModel(
            name='OppPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opponents.oppclub', verbose_name='Verein')),
            ],
        ),
        migrations.CreateModel(
            name='OppTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='OppTeamName')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opponents.oppclub')),
                ('player', models.ManyToManyField(blank=True, to='opponents.OppPlayer')),
            ],
        ),
    ]
