# Generated by Django 4.0.1 on 2022-03-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0003_alter_oppteam_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oppteam',
            name='player',
            field=models.ManyToManyField(blank=True, to='opponents.OppPlayer'),
        ),
    ]
