# Generated by Django 4.0.1 on 2022-03-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opponents', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_day', models.IntegerField(default=0, verbose_name='Spieltag')),
                ('game_link', models.URLField(blank=True, null=True, verbose_name='Turnier.de')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('home', models.BooleanField(default=True, verbose_name='Heimspiel')),
                ('winner', models.BooleanField(default=None, verbose_name='Gewonnen')),
                ('points_team', models.IntegerField(default=0, verbose_name='Punkte PSV')),
                ('points_opponents', models.IntegerField(default=0, verbose_name='Punkte Gegner')),
                ('game_admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Spiel Admin')),
                ('opp_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opponents.oppteam', verbose_name='Gegner')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Mannschaft')),
            ],
        ),
    ]
