# Generated by Django 4.0.1 on 2022-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('H', 'Heim'), ('A', 'Auswärts'), ('D', 'Unentschieden'), (None, 'Keiner')], default=None, max_length=5, verbose_name='Gewonnen'),
        ),
    ]
