# Generated by Django 4.0.1 on 2022-04-01 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='datetime',
        ),
        migrations.AddField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Endzeit'),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Startzeit'),
        ),
    ]
