# Generated by Django 4.0.1 on 2022-04-01 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_datetime_game_end_time_game_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Endzeit'),
        ),
    ]
