# Generated by Django 4.0.1 on 2022-04-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='points_opponents',
        ),
        migrations.RemoveField(
            model_name='game',
            name='points_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
