# Generated by Django 4.0.1 on 2022-04-23 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opponents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_remove_game_points_opponents_remove_game_points_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('points_opp_team', models.ManyToManyField(related_name='points_opp_team', to='livescoring.Point', verbose_name='Punkte Gegner')),
                ('points_team', models.ManyToManyField(related_name='points_team', to='livescoring.Point', verbose_name='Punkte PSV')),
            ],
        ),
        migrations.CreateModel(
            name='MatchGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('MD1', '1. Herrendoppel'), ('MD2', '2. Herrendoppel'), ('WD', 'Damendoppel'), ('MS1', '1. Herreneinzel'), ('MS2', '2. Herreneinzel'), ('MS3', '3. Herreneinzel'), ('WS', 'Dameneinzel'), ('XD', 'Gemischtes Doppel')], max_length=15, verbose_name='Spiel')),
                ('winner', models.CharField(choices=[('T', 'Team'), ('O', 'Gegner'), (None, 'Keiner')], max_length=10, verbose_name='Winner')),
                ('current_set', models.IntegerField(default=0)),
                ('player_oppTeam1', models.ManyToManyField(to='opponents.OppPlayer', verbose_name='Spieler Gegner')),
                ('player_team1', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Spieler')),
                ('sets', models.ManyToManyField(blank=True, to='livescoring.Set', verbose_name='Sätze')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('score_team', models.IntegerField(default=0, verbose_name='Punkte PSV')),
                ('score_opponents', models.IntegerField(default=0, verbose_name='Punkte Gegner')),
                ('winner', models.CharField(choices=[('H', 'Heim'), ('A', 'Auswärts'), ('D', 'Unentschieden'), (None, 'Keiner')], default=None, max_length=5, null=True, verbose_name='Gewonnen')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Spiel')),
                ('games', models.ManyToManyField(to='livescoring.MatchGame', verbose_name='Spiele')),
            ],
        ),
    ]
