# Generated by Django 4.0.1 on 2022-04-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livescoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matchgame',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='set',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
