# Generated by Django 4.0.1 on 2022-04-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livescoring', '0002_match_last_modified_matchgame_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Spiel Aktiv'),
        ),
    ]
