# Generated by Django 4.0.1 on 2022-03-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_staff',
            new_name='is_board',
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Mann'), ('F', 'Frau'), ('D', 'Divers')], default='D', max_length=5, verbose_name='Geschlecht'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
