# Generated by Django 4.0.1 on 2022-03-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Team Name')),
                ('league', models.CharField(max_length=15, verbose_name='Liga')),
                ('league_link', models.URLField(verbose_name='Turnier.de')),
                ('player', models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='Spieler')),
                ('team_capitan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_capitan', to=settings.AUTH_USER_MODEL, verbose_name='Mannschaftsführer')),
            ],
        ),
    ]
