# Generated by Django 4.0.1 on 2022-03-03 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='home',
            field=models.BooleanField(default=True, verbose_name='HomeAdvantage'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='points_opponents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='points_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.teammodel'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='winner',
            field=models.BooleanField(default=None, verbose_name='Winner'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='game_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
