# Generated by Django 4.0.1 on 2022-03-05 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_league_alter_team_league_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_gamemodel_home_gamemodel_points_opponents_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameModel',
            new_name='Game',
        ),
    ]
