# Generated by Django 4.0.1 on 2022-03-07 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_league_alter_team_league_link_and_more'),
        ('opponents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_rename_gamemodel_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opp_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opponents.oppteam', verbose_name='Gegner'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Spiel Admin'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home',
            field=models.BooleanField(default=True, verbose_name='Heimspiel'),
        ),
        migrations.AlterField(
            model_name='game',
            name='points_opponents',
            field=models.IntegerField(default=0, verbose_name='Punkte Gegner'),
        ),
        migrations.AlterField(
            model_name='game',
            name='points_team',
            field=models.IntegerField(default=0, verbose_name='Punkte PSV'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Mannschaft'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.BooleanField(default=None, verbose_name='Gewonnen'),
        ),
    ]
