# Generated by Django 4.0.1 on 2022-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_opp_team_alter_game_game_admin_alter_game_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_day',
            field=models.IntegerField(default=0, verbose_name='Spieltag'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_link',
            field=models.URLField(blank=True, null=True, verbose_name='Turnier.de'),
        ),
    ]
